#!/usr/bin/env python3
"""Turn a microWakeWord .tflite (and its manifest .json) into src/wake_word_model.h.

    python scripts/tflite_to_header.py models/rina_chan.tflite models/rina_chan.json

The manifest is the same JSON ESPHome uses (wake_word, micro.probability_cutoff,
micro.sliding_window_size, micro.tensor_arena_size, micro.feature_step_size).
"""
import json
import sys
from pathlib import Path


def main(tflite_path, manifest_path, out_path="src/wake_word_model.h"):
    data = Path(tflite_path).read_bytes()
    manifest = json.loads(Path(manifest_path).read_text())
    micro = manifest["micro"]
    cutoff = round(micro["probability_cutoff"] * 255)
    rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    Path(out_path).write_text(
        "// Generated by scripts/tflite_to_header.py from "
        f"{Path(tflite_path).name} and {Path(manifest_path).name}; do not edit.\n"
        "#pragma once\n#include <stdint.h>\n\n"
        f"#define WAKE_WORD_NAME \"{manifest['wake_word']}\"\n"
        f"#define WAKE_WORD_PROBABILITY_CUTOFF {cutoff}  // {micro['probability_cutoff']} of 255\n"
        f"#define WAKE_WORD_SLIDING_WINDOW {micro['sliding_window_size']}\n"
        f"#define WAKE_WORD_TENSOR_ARENA_SIZE {micro['tensor_arena_size']}\n"
        f"#define WAKE_WORD_FEATURE_STEP_MS {micro.get('feature_step_size', 10)}\n\n"
        f"alignas(16) static const uint8_t wake_word_model[{len(data)}] = {{\n  "
        + ",\n  ".join(rows) + "\n};\n")
    print(f"{out_path}: {manifest['wake_word']!r}, {len(data)} bytes, cutoff {cutoff}/255")


if __name__ == "__main__":
    main(*sys.argv[1:])
