// M5StickS3 push-to-talk mic/speaker bridge for bridge_server.py.
//
// Protocol over one WebSocket connection (raw PCM s16le mono @ SAMPLE_RATE
// both ways, framed with tiny text control messages):
//   BtnA held   -> client sends text "start", then binary mic chunks
//   BtnA release-> client sends text "stop"
//   server sends text "heard:<transcript>" as soon as STT finishes (not
//     truly live/word-by-word — faster-whisper transcribes a completed
//     utterance, not a stream — but prompt: it arrives right as listening
//     ends and thinking begins), then "reply:<text>", then binary audio
//     chunks, then "end" -> client plays the buffered reply. A reply text
//     starting with "(" is bridge_server.py's error-sentinel convention
//     ("(ollama error: ...)", "(didn't catch that)") — used here to pick
//     ERROR vs DONE once playback finishes.
//
// BtnA pressed while SPEAKING -> stops playback cleanly (interrupt) instead
//   of starting a new recording immediately, since the mic and speaker share
//   one I2S codec and switching modes mid-playback glitches the audio.
// BtnB click       -> reset conversation history (tells the server)
// BtnB long-press  -> toggle standby: Wi-Fi/mic/speaker off, screen dimmed.
//                     No dedicated hardware power button is wired up on this
//                     board (checked M5Unified's board table directly), so
//                     this is a software standby, not true deep sleep — the
//                     MCU keeps running and polling BtnB, which means there's
//                     no risk of the device going unresponsive and needing a
//                     USB reflash to recover. Long-press again to wake.
//
// The face is the Catppuccin Macchiato pixel-art sprite sheet (sprites.h,
// generated by tools/make_face_sprites.py from a reference PNG). Display is
// split into three independent components, each its own function: the
// character sprite, a small status line (procedural glyph, since the
// default font has no ● ◆ ♪), and a caption text area (transcript while
// listening/thinking, response while speaking/done) — none of them baked
// into the sprite images themselves. Everything drawn here (state, mic/TTS
// amplitude, transcript/response text) is already local to the Stick or
// arrives over the protocol above; nothing needs a new round-trip to render.
#include <M5Unified.h>
#include <M5GFX.h>
#include <WiFi.h>
#include <WebSocketsClient.h>
#include <math.h>
#include "secrets.h"
#include "sprites.h"

static const uint32_t SAMPLE_RATE = 16000;
static const size_t MIC_CHUNK_SAMPLES = 512;  // ~32ms/chunk

WebSocketsClient webSocket;
static M5Canvas canvas(&M5.Display);

// ---------------------------------------------------------------- palette
// Catppuccin Macchiato, official values (matches the reference sheet's own legend).
static inline uint16_t rgb565(uint8_t r, uint8_t g, uint8_t b) {
  return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3);
}
static const uint16_t COL_BASE      = rgb565(0x24, 0x27, 0x3A);
static const uint16_t COL_TEXT      = rgb565(0xCA, 0xD3, 0xF5);
static const uint16_t COL_SUBTEXT   = rgb565(0xA5, 0xAD, 0xCB);
static const uint16_t COL_GREEN     = rgb565(0xA6, 0xDA, 0x95);  // listening
static const uint16_t COL_MAUVE     = rgb565(0xC6, 0xA0, 0xF6);  // thinking
static const uint16_t COL_YELLOW    = rgb565(0xEE, 0xD4, 0x9F);  // speaking
static const uint16_t COL_TEAL      = rgb565(0x8B, 0xD5, 0xCA);  // done
static const uint16_t COL_RED       = rgb565(0xED, 0x87, 0x96);  // error / offline
static const uint16_t COL_PEACH     = rgb565(0xF5, 0xA9, 0x7F);  // interrupted / battery / charging
static const uint16_t COL_SAPPHIRE  = rgb565(0x7D, 0xC4, 0xE4);  // connecting

enum UiState {
  UI_CONNECTING, UI_IDLE, UI_LISTENING, UI_THINKING, UI_SPEAKING,
  UI_DONE, UI_ERROR, UI_INTERRUPTED, UI_DISCONNECTED, UI_SLEEPING,
  UI_LOW_BATTERY, UI_CHARGING,
};
static UiState uiState = UI_CONNECTING;
static float micLevel = 0.0f;    // live 0..1 level while listening
static float speakLevel = 0.0f;  // live 0..1 level while speaking
static uint32_t speakStartMs = 0;
static bool lastReplyWasError = false;
static String captionText;      // transcript (listening/thinking) or response (speaking/done)
static uint32_t transientUntil = 0;  // auto-revert-to-idle deadline for brief states
static UiState transientState = UI_IDLE;  // the state that deadline belongs to (see showTransient)

static const int HIST_N = 14;
static float levelHist[HIST_N] = {0};  // recent amplitude, fed by the mic and by playback
static int histPos = 0;
static uint32_t lastSpeakSampleMs = 0;

enum RecState { REC_IDLE, RECORDING };
static RecState recState = REC_IDLE;
static int16_t micBuf[MIC_CHUNK_SAMPLES];

static uint8_t *replyBuf = nullptr;
static size_t replyCap = 0;
static size_t replyLen = 0;
static bool receivingReply = false;

static float rms16(const int16_t *data, size_t n) {
  if (n == 0) return 0.0f;
  double sumsq = 0;
  for (size_t i = 0; i < n; i++) sumsq += (double)data[i] * data[i];
  float level = (sqrtf(sumsq / n) / 32768.0f) * 8.0f;  // same gain as the desktop orb
  return level > 1.0f ? 1.0f : level;
}

static void ensureReplyCap(size_t need) {
  if (replyCap >= need) return;
  size_t newCap = need + 64 * 1024;
  uint8_t *nb = (uint8_t *)ps_realloc(replyBuf, newCap);
  if (nb) {
    replyBuf = nb;
    replyCap = newCap;
  }
}

// Screen never shows raw status text — this still logs every transition to
// Serial for debugging over USB.
static void setStatus(const String &line1, const String &line2 = "") {
  Serial.printf("[status] %s %s\n", line1.c_str(), line2.c_str());
}

// ---------------------------------------------------------------- idle blink
// Every few seconds, one quick blink. Deliberately the only motion while
// idle: everything else about the frame is pinned, since anything busier
// reads as her fidgeting.
static uint32_t blinkAtMs = 0;
static uint32_t blinkEndMs = 0;

static const uint16_t *idleSprite(uint32_t t) {
  if (t >= blinkEndMs && t >= blinkAtMs) {  // schedule the next one
    blinkAtMs = t + 3500 + random(4000);
    blinkEndMs = blinkAtMs + 260;
  }
  if (t >= blinkAtMs && t < blinkEndMs) {
    return (blinkAtMs % 5 == 0) ? kSprite_blink2 : kSprite_blink;
  }
  return kSprite_idle;
}

// ---------------------------------------------------------------- character sprite
// One sprite per state, drawn at a fixed position — the sheet's own design is
// a steady character with the state conveyed by the effects around her, and
// tools/make_face_sprites.py normalises every frame to the same size and
// position so nothing shifts as states change. The two exceptions are the
// blink and the mouth, which are real animation rather than drift.
static const uint16_t *characterSpriteFor(uint32_t t) {
  switch (uiState) {
    case UI_CONNECTING:   return kSprite_disconnected;  // no "connecting" frame; not-yet-connected
    case UI_IDLE:          return idleSprite(t);
    case UI_LISTENING:     return kSprite_listening;
    case UI_THINKING:      return kSprite_thinking;
    case UI_SPEAKING:  // mouth shape follows the TTS audio's live amplitude
      if (speakLevel > 0.45f) return kSprite_mouth_wide;
      if (speakLevel > 0.25f) return kSprite_mouth_medium;
      if (speakLevel > 0.08f) return kSprite_mouth_small;
      return kSprite_mouth_closed;
    case UI_DONE:          return kSprite_done;
    case UI_ERROR:          return kSprite_error;
    case UI_INTERRUPTED:    return kSprite_surprised;
    case UI_DISCONNECTED:   return kSprite_disconnected;
    case UI_SLEEPING:       return kSprite_sleepy;
    case UI_LOW_BATTERY:    return kSprite_low_battery;
    case UI_CHARGING:       return kSprite_charging;
    default:                 return kSprite_idle;
  }
}

// ---------------------------------------------------------------- status line
// Small procedural glyphs — the default font has no ● ◆ ♪ etc.
enum Glyph { GLYPH_NONE, GLYPH_DOT, GLYPH_DIAMOND, GLYPH_NOTE, GLYPH_CHECK, GLYPH_WARN, GLYPH_BOLT, GLYPH_OFFLINE };

static void drawGlyph(Glyph g, int cx, int cy, uint16_t color) {
  switch (g) {
    case GLYPH_DOT:
      canvas.fillCircle(cx, cy, 3, color);
      break;
    case GLYPH_DIAMOND:
      canvas.fillTriangle(cx, cy - 4, cx - 4, cy, cx, cy + 4, color);
      canvas.fillTriangle(cx, cy - 4, cx + 4, cy, cx, cy + 4, color);
      break;
    case GLYPH_NOTE:
      canvas.fillCircle(cx - 2, cy + 3, 3, color);
      canvas.fillRect(cx + 1, cy - 5, 2, 8, color);
      canvas.fillRect(cx + 1, cy - 5, 4, 2, color);
      break;
    case GLYPH_CHECK:
      canvas.drawWideLine(cx - 4, cy, cx - 1, cy + 3, 2, color);
      canvas.drawWideLine(cx - 1, cy + 3, cx + 4, cy - 4, 2, color);
      break;
    case GLYPH_WARN:
      canvas.fillTriangle(cx, cy - 5, cx - 5, cy + 4, cx + 5, cy + 4, color);
      canvas.fillRect(cx - 1, cy - 2, 2, 3, COL_BASE);
      canvas.fillRect(cx - 1, cy + 3, 2, 1, COL_BASE);
      break;
    case GLYPH_BOLT:
      canvas.fillTriangle(cx + 2, cy - 5, cx - 3, cy + 1, cx + 1, cy + 1, color);
      canvas.fillTriangle(cx - 2, cy + 5, cx + 3, cy - 1, cx - 1, cy - 1, color);
      break;
    case GLYPH_OFFLINE:
      canvas.drawCircle(cx, cy + 2, 5, color);
      canvas.drawWideLine(cx - 5, cy - 5, cx + 5, cy + 5, 2, color);
      break;
    default:
      break;
  }
}

struct StatusInfo { Glyph glyph; const char *text; uint16_t color; };

static StatusInfo statusFor(UiState st) {
  switch (st) {
    case UI_CONNECTING:   return {GLYPH_DOT, "Connecting...", COL_SAPPHIRE};
    case UI_IDLE:          return {GLYPH_NONE, "Ready", COL_SUBTEXT};
    case UI_LISTENING:     return {GLYPH_DOT, "Listening...", COL_GREEN};
    case UI_THINKING:      return {GLYPH_DIAMOND, "Thinking...", COL_MAUVE};
    case UI_SPEAKING:      return {GLYPH_NOTE, "Speaking...", COL_YELLOW};
    case UI_DONE:          return {GLYPH_CHECK, "Done!", COL_TEAL};
    case UI_ERROR:          return {GLYPH_WARN, "Error!", COL_RED};
    case UI_INTERRUPTED:    return {GLYPH_WARN, "Interrupted", COL_PEACH};
    case UI_DISCONNECTED:   return {GLYPH_OFFLINE, "Offline", COL_RED};
    case UI_LOW_BATTERY:    return {GLYPH_WARN, "Low battery", COL_PEACH};
    case UI_CHARGING:       return {GLYPH_BOLT, "Charging...", COL_PEACH};
    default:                 return {GLYPH_NONE, "", COL_SUBTEXT};
  }
}

// briefly show a state, then auto-revert to idle after `ms` — guarded by
// transientState so an unrelated uiState change in the meantime (e.g. the
// Wi-Fi dropping mid-transient) doesn't get silently clobbered back to IDLE
// when this deadline fires; see loop().
static void showTransient(UiState st, uint32_t ms) {
  uiState = st;
  transientState = st;
  transientUntil = millis() + ms;
  setStatus(statusFor(st).text);
}

static const int CHAR_TOP = 2;     // sprite height (96) covers most of the 135px canvas
static const int STATUS_Y = 100;
static const int CAPTION_Y = 110;

static void drawStatusLine() {
  if (uiState == UI_SLEEPING) return;
  StatusInfo s = statusFor(uiState);
  if (!s.text[0]) return;
  int glyphW = s.glyph == GLYPH_NONE ? 0 : 12;
  int textW = (int)strlen(s.text) * 6;
  int x = canvas.width() / 2 - (glyphW + textW) / 2;
  if (s.glyph != GLYPH_NONE) {
    drawGlyph(s.glyph, x + 4, STATUS_Y + 4, s.color);
    x += glyphW;
  }
  canvas.setTextColor(s.color);
  canvas.setTextSize(1);
  canvas.setTextDatum(top_left);
  canvas.setCursor(x, STATUS_Y);
  canvas.print(s.text);
}

// ---------------------------------------------------------------- amplitude pulses
// Live amplitude, both directions: green while she's hearing you, yellow
// while she's talking (where it doubles up with her mouth shape). Drawn
// flanking her the way the sheet's own design does, in the side margins
// she doesn't occupy (120px wide on a 240px screen), which keeps it clear
// of both the sprite and the caption text.
static void drawAmplitudePulses() {
  uint16_t colour;
  if (uiState == UI_LISTENING) {
    colour = COL_GREEN;
  } else if (uiState == UI_SPEAKING) {
    colour = COL_YELLOW;
  } else {
    return;
  }
  const int bars = 5, barW = 5, step = 8;
  int cy = CHAR_TOP + kSpriteH / 2;
  for (int i = 0; i < bars; i++) {
    int idx = (histPos + HIST_N - 1 - i) % HIST_N;  // newest nearest her
    int h = 4 + (int)(levelHist[idx] * 40);
    canvas.fillRoundRect(34 - i * step, cy - h / 2, barW, h, 2, colour);
    canvas.fillRoundRect(201 + i * step, cy - h / 2, barW, h, 2, colour);
  }
}

// ---------------------------------------------------------------- caption text
// Greedy word-wrap: returns the text[startIdx..] that fits in maxChars,
// breaking on the last space at or before the limit, and reports where
// the next line should pick up via nextIdx.
static String wrapLine(const String &text, int maxChars, int startIdx, int &nextIdx) {
  int n = text.length();
  if (startIdx >= n) {
    nextIdx = startIdx;
    return "";
  }
  int end = startIdx + maxChars;
  if (end >= n) {
    nextIdx = n;
    return text.substring(startIdx);
  }
  int cut = text.lastIndexOf(' ', end);
  if (cut <= startIdx) cut = end;  // no space to break on — hard cut
  nextIdx = cut + 1;
  return text.substring(startIdx, cut);
}

static const int MAX_CAPTION_LINES = 2;
static const int MAX_CAPTION_CHARS = 36;

static void drawCaptionText() {
  if (captionText.length() == 0) return;
  if (uiState == UI_CONNECTING || uiState == UI_SLEEPING || uiState == UI_DISCONNECTED) return;

  canvas.setTextColor(COL_TEXT);
  canvas.setTextSize(1);
  canvas.setTextDatum(top_left);

  int idx = 0;
  for (int line = 0; line < MAX_CAPTION_LINES && idx < (int)captionText.length(); line++) {
    int next;
    String l = wrapLine(captionText, MAX_CAPTION_CHARS, idx, next);
    if (line == MAX_CAPTION_LINES - 1 && next < (int)captionText.length()) {
      while (l.length() > (unsigned)(MAX_CAPTION_CHARS - 3)) l.remove(l.length() - 1);
      l += "...";  // the spec asks for "…"; ASCII "..." renders correctly on any font, "…" (U+2026) may not
    }
    canvas.setCursor(4, CAPTION_Y + line * 9);
    canvas.println(l);
    idx = next;
  }
}

// ---------------------------------------------------------------- assembly
static void drawFace() {
  canvas.fillScreen(COL_BASE);

  // Fixed position, no bob: the sprites are normalised to a common size and
  // position at build time, so she stays put and only her expression changes.
  canvas.pushImage((canvas.width() - kSpriteW) / 2, CHAR_TOP, kSpriteW, kSpriteH,
                   characterSpriteFor(millis()));

  drawAmplitudePulses();
  drawStatusLine();
  drawCaptionText();

  canvas.pushSprite(0, 0);
}

static uint32_t lastDraw = 0;
static void maybeDrawFace() {
  uint32_t now = millis();
  if (now - lastDraw >= 40) {  // ~25fps
    lastDraw = now;
    drawFace();
  }
}

// ---------------------------------------------------------------- battery
// Only surfaced while idle, so it never interrupts an active conversation.
static uint32_t lastBatteryCheckMs = 0;
static bool wasCharging = false;

static void maybeCheckBattery() {
  uint32_t t = millis();
  if (t - lastBatteryCheckMs < 30000) return;
  lastBatteryCheckMs = t;
  if (uiState != UI_IDLE) return;

  bool charging = ((int)M5.Power.isCharging() == 1);  // Power_Class::is_charging_t::is_charging
  if (charging && !wasCharging) {
    showTransient(UI_CHARGING, 1500);
  }
  wasCharging = charging;

  if (!charging) {
    int lvl = M5.Power.getBatteryLevel();
    if (lvl >= 0 && lvl <= 15) {
      showTransient(UI_LOW_BATTERY, 1500);
    }
  }
}

// ---------------------------------------------------------------- network
static void webSocketEvent(WStype_t type, uint8_t *payload, size_t length) {
  switch (type) {
    case WStype_CONNECTED:
      setStatus("connected", WS_HOST);
      if (uiState == UI_DISCONNECTED || uiState == UI_CONNECTING) uiState = UI_IDLE;
      break;
    case WStype_DISCONNECTED:
      setStatus("disconnected...");
      if (uiState != UI_SLEEPING) uiState = UI_DISCONNECTED;
      break;
    case WStype_TEXT: {
      String msg((char *)payload, length);
      if (msg.startsWith("heard:")) {
        captionText = msg.substring(6);
        setStatus("heard", captionText);
      } else if (msg.startsWith("reply:")) {
        captionText = msg.substring(6);
        lastReplyWasError = captionText.startsWith("(");
        setStatus("Generating", captionText);
        receivingReply = true;
        replyLen = 0;
      } else if (msg == "end") {
        receivingReply = false;
        if (replyLen > 0) {
          M5.Mic.end();
          M5.Speaker.begin();
          M5.Speaker.playRaw((int16_t *)replyBuf, replyLen / 2, SAMPLE_RATE, false);
          speakStartMs = millis();
          uiState = UI_SPEAKING;
        } else if (lastReplyWasError) {
          showTransient(UI_ERROR, 900);
        } else {
          uiState = UI_IDLE;
        }
      }
      break;
    }
    case WStype_BIN:
      if (receivingReply) {
        ensureReplyCap(replyLen + length);
        memcpy(replyBuf + replyLen, payload, length);
        replyLen += length;
      }
      break;
    default:
      break;
  }
}

static void connectNetwork() {
  uiState = UI_CONNECTING;
  setStatus("wifi...", WIFI_SSID);
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  while (WiFi.status() != WL_CONNECTED) {
    delay(150);
    M5.update();
    maybeDrawFace();
    if (M5.BtnB.wasReleasedAfterHold()) return;  // bail out of a stuck reconnect back to standby
  }
  setStatus("wifi ok", WiFi.localIP().toString());
  webSocket.begin(WS_HOST, WS_PORT, WS_PATH);
  M5.Mic.begin();
  uiState = UI_IDLE;
}

// ---------------------------------------------------------------- standby
// Beyond cutting Wi-Fi/mic/speaker: draw the standby screen once instead of
// redrawing an unchanging frame at 25fps forever, put the panel itself in
// its low-power sleep mode (not just dim — M5GFX's sleep() also sends the
// controller its own SLPIN command), and underclock the CPU, since standby
// is doing nothing but polling one button.
static void enterStandby() {
  uiState = UI_SLEEPING;
  setStatus("standby", "hold BtnB to wake");
  webSocket.disconnect();
  WiFi.disconnect(true);
  WiFi.mode(WIFI_OFF);
  M5.Mic.end();
  M5.Speaker.end();
  drawFace();
  M5.Display.sleep();
  setCpuFrequencyMhz(80);
}

static void wakeFromStandby() {
  setCpuFrequencyMhz(240);
  M5.Display.wakeup();
  connectNetwork();
}

void setup() {
  Serial.begin(115200);
  delay(300);
  Serial.println("\n[boot] m5stick_bridge starting");

  auto cfg = M5.config();
  M5.begin(cfg);

  M5.Display.setRotation(1);
  // 16-bit to match sprites.h's RGB565 data exactly — 8-bit here was
  // forcing every pushImage() to downconvert 65536 colors to ~256,
  // mangling the pixel art. Costs ~65KB more canvas RAM (240x135x2),
  // trivial against the S3's 320KB.
  canvas.setColorDepth(16);
  canvas.createSprite(M5.Display.width(), M5.Display.height());
  // LovyanGFX's _swapBytes has inverted-sounding semantics: false (the
  // default) means "treat incoming uint16_t* as already byte-swapped",
  // true means "treat it as plain packed RGB565" — which is exactly what
  // sprites.h contains ((r<<11)|(g<<5)|b, no swapping). Without this,
  // pushImage() silently re-parses every sprite's bits in the wrong
  // layout (confirmed by tracing LGFXBase::create_pc_fast in M5GFX).
  canvas.setSwapBytes(true);

  {
    auto mic_cfg = M5.Mic.config();
    mic_cfg.sample_rate = SAMPLE_RATE;
    mic_cfg.stereo = false;
    M5.Mic.config(mic_cfg);

    auto spk_cfg = M5.Speaker.config();
    spk_cfg.sample_rate = SAMPLE_RATE;
    spk_cfg.stereo = false;
    M5.Speaker.config(spk_cfg);
    M5.Speaker.setVolume(255);  // M5Unified defaults to a conservative volume
  }

  replyCap = 200 * 1024;
  replyBuf = (uint8_t *)ps_malloc(replyCap);

  webSocket.onEvent(webSocketEvent);
  webSocket.setReconnectInterval(3000);

  connectNetwork();
}

void loop() {
  M5.update();

  if (transientUntil && millis() > transientUntil) {
    transientUntil = 0;
    if (uiState == transientState) uiState = UI_IDLE;  // else something else (e.g. a dropped
  }                                                     // connection) already moved us on

  if (M5.BtnB.wasClicked() && uiState != UI_SLEEPING) {
    webSocket.sendTXT("reset");
    setStatus("history cleared");
    captionText = "";
  }
  if (M5.BtnB.wasReleasedAfterHold()) {
    if (uiState == UI_SLEEPING) {
      wakeFromStandby();
    } else {
      enterStandby();
    }
  }

  if (uiState == UI_SLEEPING) {
    return;  // screen was drawn once on entry and is now asleep; nothing to update
  }

  webSocket.loop();
  maybeCheckBattery();

  // interrupt: stop playback cleanly rather than switching mic/speaker mid-stream
  if (uiState == UI_SPEAKING && M5.BtnA.wasPressed()) {
    M5.Speaker.stop();
    receivingReply = false;
    speakLevel = 0.0f;
    showTransient(UI_INTERRUPTED, 300);
  } else if (recState == REC_IDLE && uiState != UI_SPEAKING && uiState != UI_SLEEPING &&
             M5.BtnA.wasPressed()) {
    recState = RECORDING;
    uiState = UI_LISTENING;
    captionText = "";
    M5.Speaker.end();
    M5.Mic.begin();
    webSocket.sendTXT("start");
    setStatus("listening...");
  }

  if (recState == RECORDING) {
    if (M5.Mic.record(micBuf, MIC_CHUNK_SAMPLES, SAMPLE_RATE)) {
      micLevel = rms16(micBuf, MIC_CHUNK_SAMPLES);
      levelHist[histPos] = micLevel;
      histPos = (histPos + 1) % HIST_N;
      webSocket.sendBIN((uint8_t *)micBuf, MIC_CHUNK_SAMPLES * sizeof(int16_t));
    }
    if (M5.BtnA.wasReleased()) {
      recState = REC_IDLE;
      uiState = UI_THINKING;
      micLevel = 0.0f;
      webSocket.sendTXT("stop");
      setStatus("Processing");
    }
  }

  if (uiState == UI_SPEAKING) {
    if (M5.Speaker.isPlaying()) {
      uint32_t elapsedMs = millis() - speakStartMs;
      size_t totalSamples = replyLen / 2;
      size_t sampleIdx = (size_t)((uint64_t)elapsedMs * SAMPLE_RATE / 1000);
      size_t window = 320;  // 20ms
      if (sampleIdx >= totalSamples) {
        window = 0;
      } else if (sampleIdx + window > totalSamples) {
        window = totalSamples - sampleIdx;
      }
      speakLevel = window ? rms16((int16_t *)replyBuf + sampleIdx, window) : 0.0f;
      if (millis() - lastSpeakSampleMs >= 40) {  // same cadence the mic pushes at
        lastSpeakSampleMs = millis();
        levelHist[histPos] = speakLevel;
        histPos = (histPos + 1) % HIST_N;
      }
    } else {
      speakLevel = 0.0f;
      showTransient(lastReplyWasError ? UI_ERROR : UI_DONE, 900);
    }
  }

  maybeDrawFace();
}
