// M5StickS3 push-to-talk mic/speaker bridge for bridge_server.py.
//
// Protocol over one WebSocket connection (raw PCM s16le mono @ SAMPLE_RATE
// both ways, framed with tiny text control messages):
//   BtnA held   -> client sends text "start", then binary mic chunks
//   BtnA release-> client sends text "stop"
//   server sends text "heard:<transcript>" as soon as STT finishes (not
//     truly live/word-by-word — faster-whisper transcribes a completed
//     utterance, not a stream — but prompt: it arrives right as listening
//     ends and thinking begins), then "reply:<text>", then binary audio
//     chunks, then "end" -> client plays the buffered reply. A reply text
//     starting with "(" is bridge_server.py's error-sentinel convention
//     ("(ollama error: ...)", "(didn't catch that)") — used here to pick
//     ERROR vs DONE once playback finishes.
//
// BtnA pressed while SPEAKING -> stops playback cleanly (interrupt) instead
//   of starting a new recording immediately, since the mic and speaker share
//   one I2S codec and switching modes mid-playback glitches the audio.
// BtnA tap (otherwise)   -> cycles the display: Rina's face -> clock ->
//   pomodoro timer -> back to Rina. A tap and a hold look identical at the
//   instant of the press, so recording waits out TALK_HOLD_MS before it
//   starts; see clock_face.h and pomodoro_face.h for the two alt screens.
// BtnB click       -> reset conversation history (tells the server) on
//   Rina's face or the clock; starts/pauses the countdown on the pomodoro
//   screen instead, since there is no conversation in view there to reset
//   (double click resets the pomodoro timer to 50:00 there instead).
// Powering off is the physical power button (double-click it) -- a real
// PMIC-level power-off, confirmed against M5Stack's own docs
// (docs.m5stack.com/en/arduino/m5sticks3/button). BtnB long-press used to
// trigger ESP32 deep sleep as a software-only substitute, from before that
// button's real behavior was verified; removed 2026-09-15 now that the
// power button covers this properly (and more deeply -- true PMIC power-off
// draws less than ESP32 deep sleep, which still keeps the RTC/wake domain
// powered).
//
// The face is the Catppuccin Macchiato pixel-art sprite sheet (sprites.h,
// generated by tools/make_face_sprites.py from a reference PNG). Display is
// split into three independent components, each its own function: the
// character sprite, a small status line (procedural glyph, since the
// default font has no ● ◆ ♪), and a caption text area (transcript while
// listening/thinking, response while speaking/done) — none of them baked
// into the sprite images themselves. Everything drawn here (state, mic/TTS
// amplitude, transcript/response text) is already local to the Stick or
// arrives over the protocol above; nothing needs a new round-trip to render.
#include <M5Unified.h>
#include <M5GFX.h>
#include <WiFi.h>
#include <WebSocketsClient.h>
#include <math.h>
#include "secrets.h"
#include "sprites.h"

static const uint32_t SAMPLE_RATE = 16000;
static const size_t MIC_CHUNK_SAMPLES = 512;  // ~32ms/chunk

// How long BtnA must be held before it counts as talking rather than as a tap
// toggling the clock. 180ms was measured too tight in use: a deliberate tap
// ran ~350ms and opened the mic instead, which the bridge logged as
// "[stop] 0.35s of audio / (nothing heard)". A comfortable tap is 150-350ms,
// so this sits above that and below anything anyone would call a hold.
static const uint32_t TALK_HOLD_MS = 400;
static uint32_t btnAPressedMs = 0;
static bool btnAArmed = false;

WebSocketsClient webSocket;
static IPAddress relayHost;  // the phone's gateway IP, resolved fresh in connectNetwork()
static M5Canvas canvas(&M5.Display);

// ---------------------------------------------------------------- palette
// Catppuccin Macchiato, official values (matches the reference sheet's own legend).
static inline uint16_t rgb565(uint8_t r, uint8_t g, uint8_t b) {
  return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3);
}
static const uint16_t COL_BASE      = rgb565(0x24, 0x27, 0x3A);
static const uint16_t COL_TEXT      = rgb565(0xCA, 0xD3, 0xF5);
static const uint16_t COL_SUBTEXT   = rgb565(0xA5, 0xAD, 0xCB);
static const uint16_t COL_GREEN     = rgb565(0xA6, 0xDA, 0x95);  // listening
static const uint16_t COL_MAUVE     = rgb565(0xC6, 0xA0, 0xF6);  // thinking
static const uint16_t COL_YELLOW    = rgb565(0xEE, 0xD4, 0x9F);  // speaking
static const uint16_t COL_TEAL      = rgb565(0x8B, 0xD5, 0xCA);  // done
static const uint16_t COL_RED       = rgb565(0xED, 0x87, 0x96);  // error / offline
static const uint16_t COL_PEACH     = rgb565(0xF5, 0xA9, 0x7F);  // interrupted / battery / charging
static const uint16_t COL_SAPPHIRE  = rgb565(0x7D, 0xC4, 0xE4);  // connecting
static const uint16_t COL_LAVENDER  = rgb565(0xB7, 0xBD, 0xF8);  // idle sparkles' second color
// Added for the clock face. Kept beside the rest so there is one palette.
static const uint16_t COL_CRUST     = rgb565(0x18, 0x19, 0x26);  // clock vignette / darkest
static const uint16_t COL_MANTLE    = rgb565(0x1E, 0x20, 0x30);  // clock panel behind the time
static const uint16_t COL_SUBTEXT1  = rgb565(0xB8, 0xC0, 0xE0);  // clock date line
static const uint16_t COL_PINK      = rgb565(0xF5, 0xBD, 0xE6);  // clock sparkles
static const uint16_t COL_BLUE      = rgb565(0x8A, 0xAD, 0xF4);  // clock wifi bars

static inline uint16_t lerp565(uint16_t c0, uint16_t c1, float t) {
  if (t <= 0.0f) return c0;
  if (t >= 1.0f) return c1;
  int r0 = (c0 >> 11) & 0x1F, g0 = (c0 >> 5) & 0x3F, b0 = c0 & 0x1F;
  int r1 = (c1 >> 11) & 0x1F, g1 = (c1 >> 5) & 0x3F, b1 = c1 & 0x1F;
  int r = r0 + (int)((r1 - r0) * t);
  int g = g0 + (int)((g1 - g0) * t);
  int b = b0 + (int)((b1 - b0) * t);
  return ((r & 0x1F) << 11) | ((g & 0x3F) << 5) | (b & 0x1F);
}

// Included here, not at the top: these draw with the palette and the shared
// `canvas` declared above, rather than defining a second copy of them.
// pomodoro_face.h comes second because it reuses clock_face.h's digit font,
// ambient decorations and the AltScreen enum/currentScreen it declares.
#include "clock_face.h"
#include "pomodoro_face.h"

enum UiState {
  UI_CONNECTING, UI_IDLE, UI_LISTENING, UI_THINKING, UI_SPEAKING,
  UI_DONE, UI_ERROR, UI_INTERRUPTED, UI_DISCONNECTED,
  UI_LOW_BATTERY, UI_CHARGING,
};
static UiState uiState = UI_CONNECTING;
static float micLevel = 0.0f;    // live 0..1 level while listening
static float speakLevel = 0.0f;  // live 0..1 level while speaking
static uint32_t speakStartMs = 0;
static bool lastReplyWasError = false;
static String captionText;      // transcript (listening/thinking) or response (speaking/done)
static uint32_t transientUntil = 0;  // auto-revert-to-idle deadline for brief states
static UiState transientState = UI_IDLE;  // the state that deadline belongs to (see showTransient)

static const int HIST_N = 14;
static float levelHist[HIST_N] = {0};  // recent amplitude, fed by the mic and by playback
static int histPos = 0;
static uint32_t lastSpeakSampleMs = 0;

enum RecState { REC_IDLE, RECORDING };
static RecState recState = REC_IDLE;
static int16_t micBuf[MIC_CHUNK_SAMPLES];

static uint8_t *replyBuf = nullptr;
static size_t replyCap = 0;
static size_t replyLen = 0;
static bool receivingReply = false;

static float rms16(const int16_t *data, size_t n) {
  if (n == 0) return 0.0f;
  double sumsq = 0;
  for (size_t i = 0; i < n; i++) sumsq += (double)data[i] * data[i];
  float level = (sqrtf(sumsq / n) / 32768.0f) * 8.0f;  // same gain as the desktop orb
  return level > 1.0f ? 1.0f : level;
}

static void ensureReplyCap(size_t need) {
  if (replyCap >= need) return;
  size_t newCap = need + 64 * 1024;
  uint8_t *nb = (uint8_t *)ps_realloc(replyBuf, newCap);
  if (nb) {
    replyBuf = nb;
    replyCap = newCap;
  }
}

// Screen never shows raw status text — this still logs every transition to
// Serial for debugging over USB.
static void setStatus(const String &line1, const String &line2 = "") {
  Serial.printf("[status] %s %s\n", line1.c_str(), line2.c_str());
}

// ---------------------------------------------------------------- idle animation
// pixelart_idle.png's curated gesture frames (see tools/make_face_sprites.py's
// extract_idle_anim): a continuous slow breathing loop, interrupted every few
// seconds by one randomly chosen gesture — blink most often, look/smile/yawn/
// sleepy as rarer flourishes — that plays through its own short sequence once
// and returns to breathing. These frames are a different, smaller size than
// the rest of the sprites (kIdleAnimW x kIdleAnimH, not kSpriteW x kSpriteH)
// since they're tight headshots with no side art of their own — the sheet's
// cells sit too close together for that (see the python tool's comment) —
// so drawFace() special-cases IDLE to push this frame at its own size
// instead of the usual one.
enum IdleGesture { GESTURE_NONE, GESTURE_BLINK, GESTURE_LOOK, GESTURE_SMILE, GESTURE_YAWN, GESTURE_SLEEPY };

struct GestureFrames { const uint16_t *const *frames; int count; };

static GestureFrames framesForGesture(IdleGesture g) {
  switch (g) {
    case GESTURE_BLINK:  return {kIdleBlink,  kIdleBlinkCount};
    case GESTURE_LOOK:   return {kIdleLook,   kIdleLookCount};
    case GESTURE_SMILE:  return {kIdleSmile,  kIdleSmileCount};
    case GESTURE_YAWN:   return {kIdleYawn,   kIdleYawnCount};
    case GESTURE_SLEEPY: return {kIdleSleepy, kIdleSleepyCount};
    default:             return {kIdleBreathe, kIdleBreatheCount};
  }
}

static const uint32_t BREATHE_FRAME_MS = 550;
static const uint32_t GESTURE_FRAME_MS = 110;

static IdleGesture activeGesture = GESTURE_NONE;
static uint32_t gestureFrameStart = 0;
static uint32_t nextGestureAtMs = 4000;  // a few seconds of breathing before the first gesture

// Weighted pick — blink is by far the most common (roughly what the old
// single-blink idleSprite() did), the rest are rare enough to read as
// occasional flourishes rather than a tic.
static IdleGesture pickGesture() {
  int r = random(100);
  if (r < 55) return GESTURE_BLINK;
  if (r < 70) return GESTURE_LOOK;
  if (r < 82) return GESTURE_SMILE;
  if (r < 92) return GESTURE_YAWN;
  return GESTURE_SLEEPY;
}

static const uint16_t *idleAnimSprite(uint32_t t) {
  if (activeGesture == GESTURE_NONE) {
    if (t < nextGestureAtMs) {
      GestureFrames b = framesForGesture(GESTURE_NONE);
      return b.frames[(t / BREATHE_FRAME_MS) % b.count];
    }
    activeGesture = pickGesture();
    gestureFrameStart = t;
  }
  GestureFrames g = framesForGesture(activeGesture);
  int idx = (t - gestureFrameStart) / GESTURE_FRAME_MS;
  if (idx >= g.count) {  // gesture finished — back to breathing, schedule the next one
    activeGesture = GESTURE_NONE;
    nextGestureAtMs = t + 3500 + random(5000);
    return framesForGesture(GESTURE_NONE).frames[0];
  }
  return g.frames[idx];
}

// ---------------------------------------------------------------- character sprite
// One sprite per state, drawn at a fixed position — the sheet's own design is
// a steady character with the state conveyed by the effects around her, and
// tools/make_face_sprites.py normalises every frame to the same size and
// position so nothing shifts as states change. The exceptions are the mouth
// (real animation, not drift) and IDLE, which drawFace() special-cases
// entirely — see idleAnimSprite() above — since its frames are a different
// size, so it never reaches this function.
static const uint16_t *characterSpriteFor(uint32_t t) {
  switch (uiState) {
    case UI_CONNECTING:   return kSprite_disconnected;  // no "connecting" frame; not-yet-connected
    case UI_LISTENING:     return kSprite_listening;
    case UI_THINKING:      return kSprite_thinking;
    case UI_SPEAKING:  // mouth shape follows the TTS audio's live amplitude
      if (speakLevel > 0.45f) return kSprite_mouth_wide;
      if (speakLevel > 0.25f) return kSprite_mouth_medium;
      if (speakLevel > 0.08f) return kSprite_mouth_small;
      return kSprite_mouth_closed;
    case UI_DONE:          return kSprite_done;
    case UI_ERROR:          return kSprite_error;
    case UI_INTERRUPTED:    return kSprite_surprised;
    case UI_DISCONNECTED:   return kSprite_disconnected;
    case UI_LOW_BATTERY:    return kSprite_low_battery;
    case UI_CHARGING:       return kSprite_charging;
    default:                 return kSprite_idle;
  }
}

// ---------------------------------------------------------------- status line
// Small procedural glyphs — the default font has no ● ◆ ♪ etc.
enum Glyph {
  GLYPH_NONE, GLYPH_DOT, GLYPH_DIAMOND, GLYPH_CROSS, GLYPH_STAR, GLYPH_SQUARE,
  GLYPH_NOTE, GLYPH_CHECK, GLYPH_WARN, GLYPH_BOLT, GLYPH_OFFLINE,
};

static void drawGlyph(Glyph g, int cx, int cy, uint16_t color) {
  switch (g) {
    case GLYPH_DOT:
      canvas.fillCircle(cx, cy, 3, color);
      break;
    case GLYPH_DIAMOND:
      canvas.fillTriangle(cx, cy - 4, cx - 4, cy, cx, cy + 4, color);
      canvas.fillTriangle(cx, cy - 4, cx + 4, cy, cx, cy + 4, color);
      break;
    case GLYPH_CROSS:  // the particle field's mid-bloom shape — small "+"
      canvas.fillRect(cx - 3, cy, 7, 1, color);
      canvas.fillRect(cx, cy - 3, 1, 7, color);
      break;
    case GLYPH_STAR:  // the particle field's peak shape — bigger diamond + "+"
      canvas.fillTriangle(cx, cy - 5, cx - 5, cy, cx, cy + 5, color);
      canvas.fillTriangle(cx, cy - 5, cx + 5, cy, cx, cy + 5, color);
      canvas.fillRect(cx - 5, cy, 11, 1, color);
      canvas.fillRect(cx, cy - 5, 1, 11, color);
      break;
    case GLYPH_SQUARE:  // thinking's tiny drifting pixel motes
      canvas.fillRect(cx - 1, cy - 1, 3, 3, color);
      break;
    case GLYPH_NOTE:
      canvas.fillCircle(cx - 2, cy + 3, 3, color);
      canvas.fillRect(cx + 1, cy - 5, 2, 8, color);
      canvas.fillRect(cx + 1, cy - 5, 4, 2, color);
      break;
    case GLYPH_CHECK:
      canvas.drawWideLine(cx - 4, cy, cx - 1, cy + 3, 2, color);
      canvas.drawWideLine(cx - 1, cy + 3, cx + 4, cy - 4, 2, color);
      break;
    case GLYPH_WARN:
      canvas.fillTriangle(cx, cy - 5, cx - 5, cy + 4, cx + 5, cy + 4, color);
      canvas.fillRect(cx - 1, cy - 2, 2, 3, COL_BASE);
      canvas.fillRect(cx - 1, cy + 3, 2, 1, COL_BASE);
      break;
    case GLYPH_BOLT:
      canvas.fillTriangle(cx + 2, cy - 5, cx - 3, cy + 1, cx + 1, cy + 1, color);
      canvas.fillTriangle(cx - 2, cy + 5, cx + 3, cy - 1, cx - 1, cy - 1, color);
      break;
    case GLYPH_OFFLINE:
      canvas.drawCircle(cx, cy + 2, 5, color);
      canvas.drawWideLine(cx - 5, cy - 5, cx + 5, cy + 5, 2, color);
      break;
    default:
      break;
  }
}

struct StatusInfo { Glyph glyph; const char *text; uint16_t color; };

static StatusInfo statusFor(UiState st) {
  switch (st) {
    case UI_CONNECTING:   return {GLYPH_DOT, "Connecting...", COL_SAPPHIRE};
    case UI_IDLE:          return {GLYPH_NONE, "Ready", COL_SUBTEXT};
    case UI_LISTENING:     return {GLYPH_DOT, "Listening...", COL_GREEN};
    case UI_THINKING:      return {GLYPH_DIAMOND, "Thinking...", COL_MAUVE};
    case UI_SPEAKING:      return {GLYPH_NOTE, "Speaking...", COL_YELLOW};
    case UI_DONE:          return {GLYPH_CHECK, "Done!", COL_TEAL};
    case UI_ERROR:          return {GLYPH_WARN, "Error!", COL_RED};
    case UI_INTERRUPTED:    return {GLYPH_WARN, "Interrupted", COL_PEACH};
    case UI_DISCONNECTED:   return {GLYPH_OFFLINE, "Offline", COL_RED};
    case UI_LOW_BATTERY:    return {GLYPH_WARN, "Low battery", COL_PEACH};
    case UI_CHARGING:       return {GLYPH_BOLT, "Charging...", COL_PEACH};
    default:                 return {GLYPH_NONE, "", COL_SUBTEXT};
  }
}

// briefly show a state, then auto-revert to idle after `ms` — guarded by
// transientState so an unrelated uiState change in the meantime (e.g. the
// Wi-Fi dropping mid-transient) doesn't get silently clobbered back to IDLE
// when this deadline fires; see loop().
static void showTransient(UiState st, uint32_t ms) {
  uiState = st;
  transientState = st;
  transientUntil = millis() + ms;
  setStatus(statusFor(st).text);
}

// The sprite is 220x116 on a 240x135 canvas, cropped with a trimmed top
// margin (tools/make_face_sprites.py's TOP_MARGIN) so she sits higher in the
// frame instead of leaving a gap above her ears. Her chin lands at canvas
// y~98-105 depending on state (measured directly off the generated sprite,
// not assumed) — TEXT_BAND_Y is set past the worst of those with a real
// shoulder-height margin, checked against a montage of every state, not just
// one or two, since the SPEAKING mouth-shape frames come from a different
// reference sheet (v2, not v3) that happens to frame her a bit higher, so a
// gap that looks fine there can still crop the rest. drawFace() paints a
// solid banner over the bottom of her portrait from TEXT_BAND_Y down, and
// the caption text goes on top of that. If FINAL_H or TOP_MARGIN change,
// re-check the montage and move TEXT_BAND_Y again — don't just eyeball one
// state, that's what cropped the text into her face last time.
//
// There's no status line at all any more: expression, colour, and the side
// effects (waveform / particle field) are the only things that say what
// state she's in — see updateAndDrawSideParticles() and drawAmplitudePulses()
// below. statusFor()/StatusInfo above still exist purely to label Serial
// debug output (setStatus()), never drawn to the screen.
static const int CHAR_TOP = 2;
static const int TEXT_BAND_Y = 110;

// ---------------------------------------------------------------- amplitude pulses
// Live amplitude, both directions: green while she's hearing you, yellow
// while she's talking (where it doubles up with her mouth shape). Flanking
// her at headphone height. Her earcups (the sheet's own biggest connected
// blob per cell, same measure tools/make_face_sprites.py uses, restricted to
// the headphone y-band) sit at local sprite-x 74-152 in the worst-case state
// checked, i.e. canvas x ~84-162 once centered — but the brightness threshold
// that measurement uses doesn't catch the earcup's anti-aliased edge pixels,
// so bars right up against that measured edge still visibly overlapped it.
// nearEdge below leaves a real ~29px gap, not just a clean-on-paper one.
// HEADPHONE_CY is her earcups' vertical center (local y ~45-80, measured the
// same way) in canvas coordinates.
static const int HEADPHONE_CY = CHAR_TOP + 63;
static void drawAmplitudePulses() {
  uint16_t colour;
  if (uiState == UI_LISTENING) {
    colour = COL_GREEN;
  } else if (uiState == UI_SPEAKING) {
    colour = COL_YELLOW;
  } else {
    return;
  }
  const int bars = 5, barW = 6, step = 8;
  const int nearEdge = 55;  // clear of her earcups (~84 at headphone height)
  int cy = HEADPHONE_CY;
  for (int i = 0; i < bars; i++) {
    int idx = (histPos + HIST_N - 1 - i) % HIST_N;  // newest nearest her
    int h = 4 + (int)(levelHist[idx] * 40);
    int x = nearEdge - barW - i * step;
    canvas.fillRoundRect(x, cy - h / 2, barW, h, 2, colour);
    canvas.fillRoundRect(canvas.width() - x - barW, cy - h / 2, barW, h, 2, colour);
  }
}

// ---------------------------------------------------------------- baked sparkle twinkle
// DONE/ERROR/INTERRUPTED/LOW_BATTERY/CHARGING keep animating the sheet's own
// baked-in sparkles/icons flanking her — tools/make_face_sprites.py finds
// their real positions (any blob too small to be her, clear of her own
// body's x-range) and bakes them into sprites.h as kSparkles_<name>. This
// picks a few indices that shift every tick and only draws them for half of
// each tick, so they visibly blink rather than just relocate.
//
// IDLE/LISTENING/THINKING/SPEAKING don't use this any more — they run the
// fully procedural particle field below instead (updateAndDrawSideParticles),
// which is what the sheet either has no baked art for (SPEAKING's v2-sourced
// mouth frames) or where the brief asked for randomized/dynamic motion the
// fixed baked positions can't give.
static bool sparklesForState(UiState st, const SparkleDot **dots, int *count) {
  switch (st) {
    case UI_DONE:        *dots = kSparkles_done;        *count = kSparkleCount_done;        return true;
    case UI_ERROR:       *dots = kSparkles_error;       *count = kSparkleCount_error;       return true;
    case UI_INTERRUPTED: *dots = kSparkles_surprised;   *count = kSparkleCount_surprised;   return true;  // INTERRUPTED draws kSprite_surprised — see characterSpriteFor()
    case UI_LOW_BATTERY: *dots = kSparkles_low_battery; *count = kSparkleCount_low_battery; return true;
    case UI_CHARGING:    *dots = kSparkles_charging;    *count = kSparkleCount_charging;    return true;
    default: return false;
  }
}

static void drawSparkleTwinkle() {
  int spriteX = (canvas.width() - kSpriteW) / 2;
  uint32_t t = millis();
  const SparkleDot *dots;
  int count;
  if (!sparklesForState(uiState, &dots, &count) || count == 0) return;
  const int kActive = 3;  // how many of her real sparkles twinkle at once
  for (int k = 0; k < count && k < kActive; k++) {
    uint32_t phase = t / 300 + k * 7;  // stagger which dot each slot shows
    if ((phase / 2) % 2 != 0) continue;  // on for one tick, off for the next
    const SparkleDot &d = dots[phase % count];
    drawGlyph(GLYPH_DIAMOND, spriteX + d.x, CHAR_TOP + d.y, COL_TEXT);
  }
}

// ---------------------------------------------------------------- side particle field
// IDLE/LISTENING/THINKING/SPEAKING's effects: a small pool of particles drawn
// only in the background strips flanking her (never over her own body — x is
// always within FLANK_MARGIN of an edge), never a status word. One pool and
// one update loop serve all four states; only the "profile" (colours, count,
// life span, whether particles drift or mix in tiny squares, whether they
// avoid the headphone-height waveform band) changes per state, so switching
// states always reads as the same system changing mood, never a different
// effect popping in.
//
// Each sparkle-shaped particle runs a fixed life cycle — blank -> dot ->
// small cross -> bright star -> small cross -> dot -> blank — via a
// triangular brightness envelope (0 at birth/death, 1 at the midpoint) that
// picks both which glyph to draw and a background->colour fade, then goes
// inactive for a random respawn delay before reappearing at a fresh random
// position. THINKING's tiny squares skip the shape progression and just fade
// in/out on the same envelope while drifting slowly within their flank.
// Position, phase, life span, and respawn delay are all randomized
// per-particle and independent of the others, so the field never looks
// synchronized.
static const int MAX_PARTICLES = 8;
static const int FLANK_MARGIN = 46;  // spawn x stays within this of the left/right edge

enum ParticleShape { PSHAPE_SPARKLE, PSHAPE_SQUARE };

struct Particle {
  bool active;
  float x, y, vx, vy;
  uint32_t bornAt, lifeMs, respawnAt;
  uint16_t color;
  ParticleShape shape;
};
static Particle particles[MAX_PARTICLES];

struct ParticleProfile {
  int count;
  const uint16_t *colors;
  int nColors;
  uint32_t minLifeMs, maxLifeMs;
  uint32_t minRespawnMs, maxRespawnMs;
  bool drift;            // THINKING's slow floating motion
  bool mixSquares;       // half the pool renders as tiny fading squares instead of sparkles
  bool avoidHeadphones;  // push spawn points clear of the waveform bars' y-band
  int yLo, yHi;
};

static const uint16_t kIdleColors[]      = { COL_SAPPHIRE, COL_LAVENDER };
static const uint16_t kListeningColors[] = { COL_GREEN, COL_SAPPHIRE };
static const uint16_t kThinkingColors[]  = { COL_MAUVE };
static const uint16_t kSpeakingColors[]  = { COL_YELLOW, COL_PEACH };

static ParticleProfile profileFor(UiState st, bool *ok) {
  *ok = true;
  switch (st) {
    // sparse, slow, roams the whole flank height — the calmest profile
    case UI_IDLE:      return {8, kIdleColors,      2, 2600, 4200,  500, 2500, false, false, false, 8, 100};
    // dominated by drawAmplitudePulses()'s waveform — this is just the "a few
    // subtle sparkles farther out" the brief asked for, kept clear of the
    // bars' band around HEADPHONE_CY
    case UI_LISTENING: return {3, kListeningColors, 2, 1800, 2800,  800, 2000, false, false, true,  8, 100};
    // busiest and fastest profile, with drifting squares mixed in
    case UI_THINKING:  return {8, kThinkingColors,  1, 1400, 2400,  300, 1200, true,  true,  false, 8, 100};
    // same shape as LISTENING's, warm-coloured, also clear of the bars
    case UI_SPEAKING:  return {3, kSpeakingColors,  2, 1800, 2800,  800, 2000, false, false, true,  8, 100};
    default:
      *ok = false;
      return {0, kIdleColors, 0, 0, 0, 0, 0, false, false, false, 0, 0};
  }
}

static float pickSpawnX() {
  bool leftSide = random(2) == 0;
  float local = 6 + (float)random(1000) / 1000.0f * (FLANK_MARGIN - 6);  // 6..FLANK_MARGIN
  return leftSide ? local : (canvas.width() - local);
}

static float pickSpawnY(int yLo, int yHi, bool avoidHeadphones) {
  float y = yLo + (float)random(1000) / 1000.0f * (yHi - yLo);
  if (avoidHeadphones) {
    const int bandLo = HEADPHONE_CY - 22, bandHi = HEADPHONE_CY + 22;
    if (y > bandLo && y < bandHi) y = (y < HEADPHONE_CY) ? bandLo - 6 : bandHi + 6;
  }
  return y;
}

// immediate=false staggers a freshly-entered state's first appearance instead
// of popping every slot on at once.
static void spawnParticle(Particle &p, const ParticleProfile &prof, uint32_t now, bool immediate) {
  p.x = pickSpawnX();
  p.y = pickSpawnY(prof.yLo, prof.yHi, prof.avoidHeadphones);
  p.vx = p.vy = 0;
  if (prof.drift) {
    p.vx = (random(200) - 100) / 4000.0f;  // px/ms, tiny
    p.vy = (random(200) - 100) / 6000.0f;
  }
  p.color = prof.colors[random(prof.nColors)];
  p.shape = (prof.mixSquares && random(2) == 0) ? PSHAPE_SQUARE : PSHAPE_SPARKLE;
  p.lifeMs = prof.minLifeMs + random(prof.maxLifeMs - prof.minLifeMs + 1);
  p.bornAt = now;
  if (immediate) {
    p.active = true;
    p.respawnAt = 0;
  } else {
    p.active = false;
    p.respawnAt = now + random(prof.maxRespawnMs);
  }
}

static UiState particleProfileState = UI_CONNECTING;  // sentinel: forces (re)init on first real use
static uint32_t lastParticleFrameMs = 0;

static void updateAndDrawSideParticles() {
  bool ok;
  ParticleProfile prof = profileFor(uiState, &ok);
  if (!ok) {
    particleProfileState = UI_CONNECTING;  // re-arm the reinit for next time one of the 4 states is entered
    return;
  }

  uint32_t now = millis();
  if (uiState != particleProfileState) {
    particleProfileState = uiState;
    lastParticleFrameMs = 0;  // avoid one huge drift step from a stale timestamp
    for (int i = 0; i < MAX_PARTICLES; i++) particles[i].active = false;
    for (int i = 0; i < prof.count && i < MAX_PARTICLES; i++) spawnParticle(particles[i], prof, now, false);
  }
  uint32_t dt = lastParticleFrameMs ? (now - lastParticleFrameMs) : 0;
  lastParticleFrameMs = now;

  for (int i = 0; i < prof.count && i < MAX_PARTICLES; i++) {
    Particle &p = particles[i];
    if (!p.active) {
      if (now >= p.respawnAt) spawnParticle(p, prof, now, true);
      continue;
    }
    uint32_t age = now - p.bornAt;
    if (age >= p.lifeMs) {
      p.active = false;
      p.respawnAt = now + prof.minRespawnMs + random(prof.maxRespawnMs - prof.minRespawnMs + 1);
      continue;
    }
    if (prof.drift && dt) {
      p.x += p.vx * dt;
      p.y += p.vy * dt;
      // bounce back toward its own edge if drift carries it over her body
      if (p.x > FLANK_MARGIN && p.x < canvas.width() - FLANK_MARGIN) p.vx = -p.vx;
      if (p.y < 8 || p.y > 100) p.vy = -p.vy;
    }
    float t = (float)age / (float)p.lifeMs;          // 0..1 across the whole life
    float env = 1.0f - fabsf(2.0f * t - 1.0f);        // triangular envelope, peaks at t=0.5
    if (env <= 0.06f) continue;                        // effectively blank
    uint16_t c = lerp565(COL_BASE, p.color, env);
    if (p.shape == PSHAPE_SQUARE) {
      drawGlyph(GLYPH_SQUARE, (int)p.x, (int)p.y, c);
    } else {
      Glyph g = env < 0.28f ? GLYPH_DOT : (env < 0.62f ? GLYPH_CROSS : GLYPH_STAR);
      drawGlyph(g, (int)p.x, (int)p.y, c);
    }
  }
}

// ---------------------------------------------------------------- caption text
// Greedy word-wrap: returns the text[startIdx..] that fits in maxChars,
// breaking on the last space at or before the limit, and reports where
// the next line should pick up via nextIdx.
static String wrapLine(const String &text, int maxChars, int startIdx, int &nextIdx) {
  int n = text.length();
  if (startIdx >= n) {
    nextIdx = startIdx;
    return "";
  }
  int end = startIdx + maxChars;
  if (end >= n) {
    nextIdx = n;
    return text.substring(startIdx);
  }
  int cut = text.lastIndexOf(' ', end);
  if (cut <= startIdx) cut = end;  // no space to break on — hard cut
  nextIdx = cut + 1;
  return text.substring(startIdx, cut);
}

static const int MAX_CAPTION_CHARS = 36;

// There's no status line taking up a row any more (see the note above
// TEXT_BAND_Y), so the whole banner below it is the caption's: fixed at 3
// lines since replies are intentionally short, and 111 + 3*CAPTION_LINE_H
// lands exactly on the canvas's bottom edge (135) — checked against
// TEXT_BAND_Y, not eyeballed, same rule as that constant.
static const int CAPTION_Y = 111;
static const int CAPTION_LINE_H = 8;
static const int MAX_CAPTION_LINES = 3;

// Listening shows the transcript once STT delivers it ("heard:" — see the
// protocol note at the top of this file); thinking keeps that same text
// visible until "reply:" replaces it; speaking/done show the reply. No
// separate state word anywhere — this is the only text on screen.
static void drawCaptionText() {
  if (captionText.length() == 0) return;
  if (uiState == UI_CONNECTING || uiState == UI_DISCONNECTED) return;

  canvas.setTextColor(COL_TEXT);
  canvas.setTextSize(1);
  canvas.setTextDatum(top_left);

  int idx = 0;
  for (int line = 0; line < MAX_CAPTION_LINES && idx < (int)captionText.length(); line++) {
    int next;
    String l = wrapLine(captionText, MAX_CAPTION_CHARS, idx, next);
    if (line == MAX_CAPTION_LINES - 1 && next < (int)captionText.length()) {
      while (l.length() > (unsigned)(MAX_CAPTION_CHARS - 3)) l.remove(l.length() - 1);
      l += "...";  // the spec asks for "…"; ASCII "..." renders correctly on any font, "…" (U+2026) may not
    }
    canvas.setCursor(4, CAPTION_Y + line * CAPTION_LINE_H);
    canvas.println(l);
    idx = next;
  }
}

// ---------------------------------------------------------------- assembly
static void drawFace() {
  canvas.fillScreen(COL_BASE);

  // Fixed position, no bob: the sprites are normalised to a common size and
  // position at build time, so she stays put and only her expression changes.
  // IDLE alone uses its own smaller, differently-proportioned frames (see
  // idleAnimSprite()'s comment), so it gets its own pushImage size here.
  if (uiState == UI_IDLE) {
    canvas.pushImage((canvas.width() - kIdleAnimW) / 2, CHAR_TOP, kIdleAnimW, kIdleAnimH,
                     idleAnimSprite(millis()));
  } else {
    canvas.pushImage((canvas.width() - kSpriteW) / 2, CHAR_TOP, kSpriteW, kSpriteH,
                     characterSpriteFor(millis()));
  }

  // Solid banner over the bottom of her portrait — see TEXT_BAND_Y's comment —
  // so the caption text always sits on a clean background regardless of what's
  // drawn there in the sprite underneath.
  canvas.fillRect(0, TEXT_BAND_Y, canvas.width(), canvas.height() - TEXT_BAND_Y, COL_BASE);

  drawAmplitudePulses();          // listening/speaking: waveform beside the headphones
  updateAndDrawSideParticles();   // idle/listening/thinking/speaking: procedural particle field
  drawSparkleTwinkle();           // done/error/interrupted/low_battery/charging: baked sparkle art
  drawCaptionText();

  canvas.pushSprite(0, 0);
}

static uint32_t lastDraw = 0;
static void maybeDrawFace() {
  uint32_t now = millis();
  if (now - lastDraw >= 90) {  // ~11fps — plenty for this animation, easy on the S3
    lastDraw = now;
    drawFace();
  }
}

// ---------------------------------------------------------------- battery
// Only surfaced while idle, so it never interrupts an active conversation.
static uint32_t lastBatteryCheckMs = 0;
static bool wasCharging = false;

static void maybeCheckBattery() {
  uint32_t t = millis();
  if (t - lastBatteryCheckMs < 30000) return;
  lastBatteryCheckMs = t;
  if (uiState != UI_IDLE) return;

  bool charging = ((int)M5.Power.isCharging() == 1);  // Power_Class::is_charging_t::is_charging
  if (charging && !wasCharging) {
    showTransient(UI_CHARGING, 1500);
  }
  wasCharging = charging;

  if (!charging) {
    int lvl = M5.Power.getBatteryLevel();
    if (lvl >= 0 && lvl <= 15) {
      showTransient(UI_LOW_BATTERY, 1500);
    }
  }
}

// ---------------------------------------------------------------- network
static void webSocketEvent(WStype_t type, uint8_t *payload, size_t length) {
  switch (type) {
    case WStype_CONNECTED:
      setStatus("connected", relayHost.toString());
      if (uiState == UI_DISCONNECTED || uiState == UI_CONNECTING) uiState = UI_IDLE;
      break;
    case WStype_DISCONNECTED:
      setStatus("disconnected...");
      uiState = UI_DISCONNECTED;
      break;
    case WStype_TEXT: {
      String msg((char *)payload, length);
      if (msg.startsWith("heard:")) {
        captionText = msg.substring(6);
        setStatus("heard", captionText);
      } else if (msg.startsWith("status:")) {
        // An agent backend reporting a tool it is running ("searching the
        // web"). Only the caption changes: the state stays THINKING, so the
        // mauve particle field keeps running underneath and the screen shows
        // work happening instead of a frozen transcript. Plain chat backends
        // never send this.
        captionText = msg.substring(7);
        setStatus("status", captionText);
      } else if (msg.startsWith("reply:")) {
        captionText = msg.substring(6);
        lastReplyWasError = captionText.startsWith("(");
        setStatus("Generating", captionText);
        receivingReply = true;
        replyLen = 0;
      } else if (msg == "end") {
        receivingReply = false;
        if (replyLen > 0) {
          M5.Mic.end();
          M5.Speaker.begin();
          M5.Speaker.playRaw((int16_t *)replyBuf, replyLen / 2, SAMPLE_RATE, false);
          speakStartMs = millis();
          uiState = UI_SPEAKING;
        } else if (lastReplyWasError) {
          showTransient(UI_ERROR, 900);
        } else {
          uiState = UI_IDLE;
        }
      }
      break;
    }
    case WStype_BIN:
      if (receivingReply) {
        ensureReplyCap(replyLen + length);
        memcpy(replyBuf + replyLen, payload, length);
        replyLen += length;
      }
      break;
    default:
      break;
  }
}

static void connectNetwork() {
  uiState = UI_CONNECTING;
  setStatus("wifi...", WIFI_SSID);
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  while (WiFi.status() != WL_CONNECTED) {
    delay(150);
    M5.update();
    maybeDrawFace();
  }
  setStatus("wifi ok", WiFi.localIP().toString());
  // The phone (running tools/termux_relay.py) IS this Wi-Fi's AP, so it's
  // always our DHCP-assigned gateway — no hardcoded IP to go stale every
  // time Android rotates the hotspot's subnet on restart, and nothing to
  // reflash for. (Only valid because the Stick always joins the phone's own
  // hotspot now, never a laptop's Wi-Fi directly — see the header comment.)
  // SNTP with America/New_York rules. Started here rather than in setup()
  // because it needs an association first; once it lands, the ESP32's own RTC
  // carries the clock and the hotspot can come and go.
  clockBeginNtp();
  relayHost = WiFi.gatewayIP();
  Serial.printf("[status] relay %s\n", relayHost.toString().c_str());
  webSocket.begin(relayHost, WS_PORT, WS_PATH);
  M5.Mic.begin();
  uiState = UI_IDLE;
}

// ---------------------------------------------------------------- audio config
// Called once, from setup(). The board's defaults are not ours, so this has to
// run — but it does NOT need repeating on every M5.Mic.begin(), even though the
// mic and speaker share one I2S peripheral and playback tears the mic down
// (M5.Mic.end() before M5.Speaker.begin()). M5Unified's Mic_Class keeps _cfg as
// a plain member; end() uninstalls the I2S driver but never touches it, and
// begin() reinstalls from those same retained values. A re-assert between turns
// was tried as a fix for speaker verification scoring the same person 0.75 on
// her first utterance and 0.17-0.60 after — it was a self-assignment and fixed
// nothing. The real cause was an enrollment captured with no playback between
// samples; see CLAUDE.md.
static void applyMicConfig() {
  auto mic_cfg = M5.Mic.config();
  mic_cfg.sample_rate = SAMPLE_RATE;
  mic_cfg.stereo = false;
  M5.Mic.config(mic_cfg);
}

void setup() {
  Serial.begin(115200);
  delay(300);
  Serial.println("\n[boot] m5stick_bridge starting");

  auto cfg = M5.config();
  M5.begin(cfg);

  // Does this board actually carry a battery-backed RTC chip? M5Unified has no
  // StickS3 entry in RTC_Class's board switch, so it falls through to probing
  // for a PCF8563 — isEnabled() is the only honest answer, and it decides
  // whether the clock can survive a power cycle or only a reboot.
  {
    bool rtc = M5.Rtc.isEnabled();
    Serial.printf("[rtc] hardware RTC present: %s\n", rtc ? "yes" : "no");
    if (rtc) {
      auto d = M5.Rtc.getDate();
      Serial.printf("[rtc] holding %04d-%02d-%02d\n", d.year, d.month, d.date);
    }
  }
  M5.Display.setRotation(1);
  // The panel is a real backlit LCD (Panel_ST7789, PWM backlight on GPIO 38 --
  // verified in M5GFX's board config, not an OLED), so the backlight is a
  // genuine, non-trivial draw on battery -- M5GFX defaults it near max.
  // 0-255 range; dimmed for battery life while staying readable.
  M5.Display.setBrightness(80);
  // 16-bit to match sprites.h's RGB565 data exactly — 8-bit here was
  // forcing every pushImage() to downconvert 65536 colors to ~256,
  // mangling the pixel art. Costs ~65KB more canvas RAM (240x135x2),
  // trivial against the S3's 320KB.
  canvas.setColorDepth(16);
  canvas.createSprite(M5.Display.width(), M5.Display.height());
  // LovyanGFX's _swapBytes has inverted-sounding semantics: false (the
  // default) means "treat incoming uint16_t* as already byte-swapped",
  // true means "treat it as plain packed RGB565" — which is exactly what
  // sprites.h contains ((r<<11)|(g<<5)|b, no swapping). Without this,
  // pushImage() silently re-parses every sprite's bits in the wrong
  // layout (confirmed by tracing LGFXBase::create_pc_fast in M5GFX).
  canvas.setSwapBytes(true);

  {
    applyMicConfig();

    auto spk_cfg = M5.Speaker.config();
    spk_cfg.sample_rate = SAMPLE_RATE;
    spk_cfg.stereo = false;
    M5.Speaker.config(spk_cfg);
    // Full volume, per request. M5Stack's own hardware notice for this board
    // says to stay below 75% (191/255) on battery (no USB) to avoid an
    // excessive-draw brownout reboot — this Stick does run on battery away
    // from the laptop, so that risk is real, not just theoretical. Drop back
    // to 190 if reboots start happening during loud playback on battery.
    M5.Speaker.setVolume(255);
  }

  replyCap = 200 * 1024;
  replyBuf = (uint8_t *)ps_malloc(replyCap);

  webSocket.onEvent(webSocketEvent);
  webSocket.setReconnectInterval(3000);

  connectNetwork();
}

void loop() {
  M5.update();

  if (transientUntil && millis() > transientUntil) {
    transientUntil = 0;
    if (uiState == transientState) uiState = UI_IDLE;  // else something else (e.g. a dropped
  }                                                     // connection) already moved us on

  if (currentScreen == SCREEN_POMODORO) {
    // No conversation in view to reset here, so BtnB gets screen-local
    // meanings instead: single click start/pauses, double click resets.
    // wasSingleClicked()/wasDoubleClicked() rather than wasClicked() — the
    // latter fires on every raw release, including each half of a double
    // click, which would toggle run/pause twice before the reset ever landed.
    // The cost is the ~500ms multi-click window before a single click here
    // takes effect; imperceptible for starting a 50-minute timer, which is
    // why the other screens keep the instant wasClicked() below instead.
    if (M5.BtnB.wasDoubleClicked()) {
      pomodoroReset();
    } else if (M5.BtnB.wasSingleClicked()) {
      pomodoroToggleRun();
    }
  } else if (M5.BtnB.wasClicked()) {
    webSocket.sendTXT("reset");
    setStatus("history cleared");
    captionText = "";
  }

  webSocket.loop();
  maybeCheckBattery();

  // interrupt: stop playback cleanly rather than switching mic/speaker mid-stream
  if (uiState == UI_SPEAKING && M5.BtnA.wasPressed()) {
    M5.Speaker.stop();
    receivingReply = false;
    speakLevel = 0.0f;
    showTransient(UI_INTERRUPTED, 300);
  } else {
    // BtnA is now overloaded: a tap cycles the display, a hold still talks.
    // Recording therefore cannot start on the press itself — at that instant a
    // tap and a hold are identical — so it waits out TALK_HOLD_MS first. That
    // delay is not lost audio in practice: M5.Mic.begin() has to spin the I2S
    // driver up anyway, and people press before they start speaking.
    if (M5.BtnA.wasPressed()) {
      btnAPressedMs = millis();
      btnAArmed = true;
    }
    if (btnAArmed && recState == REC_IDLE && M5.BtnA.isPressed() &&
        millis() - btnAPressedMs >= TALK_HOLD_MS &&
        uiState != UI_SPEAKING) {
      btnAArmed = false;  // consumed as a hold, so the release won't toggle
      recState = RECORDING;
      uiState = UI_LISTENING;
      currentScreen = SCREEN_RINA;  // being spoken to beats being consulted
      captionText = "";
      M5.Speaker.end();
      M5.Mic.begin();  // _cfg survives the speaker cycle; no re-config needed
      webSocket.sendTXT("start");
      setStatus("listening...");
    }
    if (M5.BtnA.wasReleased()) {
      if (btnAArmed && recState == REC_IDLE) {  // let go before the hold — a tap
        currentScreen = (AltScreen)((currentScreen + 1) % SCREEN_COUNT);
        switch (currentScreen) {
          case SCREEN_RINA:     lastDraw = 0; break;  // repaint over the alt screen
          case SCREEN_CLOCK:    clockFaceInvalidate(); break;
          case SCREEN_POMODORO: pomodoroFaceInvalidate(); break;
          default: break;
        }
      }
      btnAArmed = false;
    }
  }

  if (recState == RECORDING) {
    if (M5.Mic.record(micBuf, MIC_CHUNK_SAMPLES, SAMPLE_RATE)) {
      micLevel = rms16(micBuf, MIC_CHUNK_SAMPLES);
      levelHist[histPos] = micLevel;
      histPos = (histPos + 1) % HIST_N;
      webSocket.sendBIN((uint8_t *)micBuf, MIC_CHUNK_SAMPLES * sizeof(int16_t));
    }
    if (M5.BtnA.wasReleased()) {
      recState = REC_IDLE;
      uiState = UI_THINKING;
      micLevel = 0.0f;
      webSocket.sendTXT("stop");
      setStatus("Processing");
    }
  }

  if (uiState == UI_SPEAKING) {
    if (M5.Speaker.isPlaying()) {
      uint32_t elapsedMs = millis() - speakStartMs;
      size_t totalSamples = replyLen / 2;
      size_t sampleIdx = (size_t)((uint64_t)elapsedMs * SAMPLE_RATE / 1000);
      size_t window = 320;  // 20ms
      if (sampleIdx >= totalSamples) {
        window = 0;
      } else if (sampleIdx + window > totalSamples) {
        window = totalSamples - sampleIdx;
      }
      speakLevel = window ? rms16((int16_t *)replyBuf + sampleIdx, window) : 0.0f;
      if (millis() - lastSpeakSampleMs >= 40) {  // same cadence the mic pushes at
        lastSpeakSampleMs = millis();
        levelHist[histPos] = speakLevel;
        histPos = (histPos + 1) % HIST_N;
      }
    } else {
      speakLevel = 0.0f;
      showTransient(lastReplyWasError ? UI_ERROR : UI_DONE, 900);
    }
  }

  // Battery/link/twinkle and the pomodoro countdown are independent of which
  // screen is on top — a screen switched away from must not go stale, and the
  // timer must keep counting down in the background so switching back to it
  // (or to Rina, or the clock) mid-session shows the right remaining time.
  screenAmbientTick();
  pomodoroTick();
  switch (currentScreen) {
    case SCREEN_CLOCK:    clockFaceTick(); break;
    case SCREEN_POMODORO: pomodoroFaceTick(); break;
    default:              maybeDrawFace(); break;
  }
}
