#!/usr/bin/env bash
# Regenerates firmware/m5stick_speak_test/src/clip.h from a line of text via
# the real VITS voice, for a speaker-only hardware test (see
# firmware/m5stick_speak_test/). Needs the `uma-tts` conda env and ffmpeg.
#
#   ./tools/make_test_clip.sh "Hi, how are you doing?"
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEXT="${1:-Hi, how are you doing?}"
SPEAKER="${2:-10}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate uma-tts
python "$HERE/tts_cli.py" "$TEXT" -m trilingual -l en -s "$SPEAKER" --device cpu -o "$TMP/clip.wav"

ffmpeg -y -hide_banner -loglevel error -i "$TMP/clip.wav" -ac 1 -ar 16000 -f s16le "$TMP/clip.pcm"

python3 - "$TMP/clip.pcm" "$HERE/firmware/m5stick_speak_test/src/clip.h" "$TEXT" <<'EOF'
import struct
import sys

pcm_path, out_path, text = sys.argv[1:4]
data = open(pcm_path, "rb").read()
n_samples = len(data) // 2
samples = struct.unpack(f"<{n_samples}h", data[:n_samples * 2])

with open(out_path, "w") as f:
    f.write(f"// Generated by tools/make_test_clip.sh from: {text!r}\n")
    f.write("// 16kHz mono s16le. Regenerate with that script, don't hand-edit.\n")
    f.write("#pragma once\n#include <cstdint>\n\n")
    f.write("static const uint32_t kClipSampleRate = 16000;\n")
    f.write(f"static const size_t kClipSampleCount = {n_samples};\n")
    f.write("static const int16_t kClipSamples[] = {\n")
    for i in range(0, n_samples, 16):
        row = samples[i:i + 16]
        f.write("  " + ",".join(str(s) for s in row) + ",\n")
    f.write("};\n")

print(f"wrote {out_path} ({n_samples} samples, {n_samples/16000:.2f}s)")
EOF
