#!/usr/bin/env python3
"""Extracts the 12 face states from the reference pixel-art sheet
(pixel_art.png, a 4x3 grid of labeled cards) and emits
firmware/m5stick_bridge/src/sprites.h — RGB565 bitmaps ready for
M5GFX's canvas.pushImage(). Crop coordinates below are specific to that
sheet's exact layout; re-run this (and re-check the crops) if the source
image changes.

    python3 tools/make_face_sprites.py /path/to/pixel_art.png
"""
import sys

from PIL import Image

SPRITE_W, SPRITE_H = 132, 100  # ~245:185 source aspect; leaves a strip at the bottom for reply text

# (name, row, col) — row/col within the 4-col x 3-row grid of cards.
STATES = [
    ("idle", 0, 0), ("listening", 0, 1), ("thinking_a", 0, 2), ("thinking_b", 0, 3),
    ("speaking_low", 1, 0), ("speaking_mid", 1, 1), ("speaking_high", 1, 2), ("blink", 1, 3),
    ("success", 2, 0), ("error", 2, 1), ("interrupted", 2, 2), ("idle_alt", 2, 3),
]

# Empirically-picked per-row face crop (within each 350x305 card) — the card
# layout isn't perfectly uniform row to row (row 1's title sits lower).
ROW_Y = {0: (50, 235), 1: (70, 255), 2: (50, 235)}
FACE_X = (55, 300)


def rgb565_values(img):
    """Standard packed RGB565 (R in the top 5 bits), one uint16_t per pixel —
    what M5GFX's pushImage(x, y, w, h, const uint16_t*) expects; it handles
    any SPI-level byte swapping internally, so no manual endian juggling here."""
    img = img.convert("RGB").resize((SPRITE_W, SPRITE_H), Image.LANCZOS)
    vals = []
    for y in range(SPRITE_H):
        for x in range(SPRITE_W):
            r, g, b = img.getpixel((x, y))
            vals.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
    return vals


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "/mnt/c/Users/User/WSL/pixel_art.png"
    sheet = Image.open(src)
    top, bottom = 78, sheet.size[1] - 130
    cols, rows = 4, 3
    cell_w = sheet.size[0] / cols
    cell_h = (bottom - top) / rows

    out_path = "firmware/m5stick_bridge/src/sprites.h"
    with open(out_path, "w") as f:
        f.write("// Generated by tools/make_face_sprites.py from the reference pixel-art sheet.\n")
        f.write("// Packed RGB565, %dx%d each. Don't hand-edit — regenerate instead.\n" % (SPRITE_W, SPRITE_H))
        f.write("#pragma once\n#include <cstdint>\n\n")
        f.write(f"static const int kSpriteW = {SPRITE_W};\n")
        f.write(f"static const int kSpriteH = {SPRITE_H};\n\n")

        for name, r, c in STATES:
            x0 = int(c * cell_w)
            y0 = int(top + r * cell_h)
            cell = sheet.crop((x0, y0, int(x0 + cell_w), int(y0 + cell_h)))
            fy0, fy1 = ROW_Y[r]
            face = cell.crop((FACE_X[0], fy0, FACE_X[1], fy1))
            vals = rgb565_values(face)

            f.write(f"static const uint16_t kSprite_{name}[] = {{\n")
            for i in range(0, len(vals), 16):
                f.write("  " + ",".join(str(v) for v in vals[i:i + 16]) + ",\n")
            f.write("};\n\n")

        f.write("struct Sprite { const uint16_t *data; };\n")
        f.write("enum SpriteId { ")
        f.write(", ".join(f"SPR_{name.upper()}" for name, _, _ in STATES))
        f.write(" };\n")
        f.write("static const Sprite kSprites[] = {\n")
        for name, _, _ in STATES:
            f.write(f"  {{ kSprite_{name} }},\n")
        f.write("};\n")

    print(f"wrote {out_path} ({len(STATES)} sprites, {SPRITE_W}x{SPRITE_H} each, "
          f"~{len(STATES) * SPRITE_W * SPRITE_H * 2 // 1024}KB)")


if __name__ == "__main__":
    main()
